More GHA release fixes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -55,11 +55,13 @@ jobs:
       - name: Build the collection
         run: ansible-galaxy collection build -v --force community.molecule
       - name: Publish the collection on Galaxy
-        if: "${{ secrets.ansible_galaxy_api_key }}"
+        if: env.ANSIBLE_GALAXY_API_KEY != ''
+        env:
+          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ansible_galaxy_api_key }}
         run: |
-          [[ "${{ secrets.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 1; }
+          [[ "$ANSIBLE_GALAXY_API_KEY" ]] || { echo "ANSIBLE_GALAXY_API_KEY is required to publish on galaxy" ; exit 1; }
           TARBALL=$(ls -1 ./*.tar.gz)
-          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
+          ansible-galaxy collection publish "${TARBALL}" --api-key "$ANSIBLE_GALAXY_API_KEY"
 
   forum_post:
     if: "${{ github.event_name == 'release' }}"
